apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-data-processing-service
  namespace: secure-data-processing
spec:
  podSelector:
    matchLabels:
      app: secure-data-processing-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
