FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY apps/worker ./apps/worker
RUN npm install
RUN npm run build:core
WORKDIR /app/apps/worker
RUN npm install
CMD ["npm", "run", "dev"]
