FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY apps/realtime ./apps/realtime
RUN npm install
RUN npm run build:core
WORKDIR /app/apps/realtime
RUN npm install
EXPOSE 8090
CMD ["npm", "run", "dev"]
