FROM node:22-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY apps/api ./apps/api
RUN npm install
RUN npm run build:core
WORKDIR /app/apps/api
RUN npm install
EXPOSE 8080
CMD ["npm", "run", "dev"]
